<a href="https://colab.research.google.com/github/YTChiew/World-Internet-Usage-Data-Analyst/blob/main/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Notebook Title: World Internet Usage Analysis
# Author: YTChiew
# Date: 2026-03-31
# Project: GitHub portfolio

In [2]:
#import libraries
import pandas as pd
import numpy as np

In [3]:
#load dataset
df = pd.read_csv('/content/internet_users.csv')
df.head()

,Location,Rate (WB),Year,Rate (ITU),Year.1,Users (CIA),Year.2,Notes
0,World,67.4,2023.0,67.4,2023.0,NaN,NaN,NaN
1,Afghanistan,18.4,2020.0,17.6,2019.0,7020000.0,2020.0,NaN
2,Albania,83.1,2023.0,83.1,2023.0,2291000.0,2021.0,NaN
3,Algeria,71.2,2022.0,71.2,2022.0,31240000.0,2021.0,NaN
4,American Samoa,NaN,NaN,NaN,NaN,18135.0,2021.0,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     238 non-null    object
 1   Rate (WB)    209 non-null    float64
 2   Year         209 non-null    float64
 3   Rate (ITU)   227 non-null    float64
 4   Year.1       227 non-null    float64
 5   Users (CIA)  232 non-null    float64
 6   Year.2       231 non-null    float64
 7   Notes        2 non-null      object
dtypes: float64(6), object(2)
memory usage: 15.0+ KB

In [5]:
df.describe()

,Rate (WB),Year,Rate (ITU),Year.1,Users (CIA),Year.2
count,209.000000,209.000000,227.000000,227.000000,2.320000e+02,231.000000
mean,70.726794,2021.497608,68.581498,2020.991189,2.100017e+07,2021.047619
std,25.065249,1.721260,26.472938,3.572252,8.427049e+07,0.232904
min,10.000000,2016.000000,1.200000,2000.000000,3.700000e+01,2020.000000
25%,54.400000,2021.000000,46.000000,2022.000000,2.537000e+05,2021.000000
50%,78.700000,2022.000000,77.700000,2022.000000,3.077700e+06,2021.000000
75%,89.900000,2022.000000,89.450000,2023.000000,9.945000e+06,2021.000000
max,100.000000,2023.000000,100.000000,2023.000000,1.022000e+09,2022.000000

In [7]:
#Clean column names

df.columns = [
    'country',
    'rate_wb',
    'year_wb',
    'rate_itu',
    'year_itu',
    'users_cia',
    'year_cia',
    'notes'
]

In [8]:
#Check for null values:
df.isnull().sum()

country        0
rate_wb       29
year_wb       29
rate_itu      11
year_itu      11
users_cia      6
year_cia       7
notes        236
dtype: int64

In [9]:
#drop column
df = df.drop(columns=['notes'])
df.head()

          country  rate_wb  year_wb  rate_itu  year_itu   users_cia  year_cia
0           World     67.4   2023.0      67.4    2023.0         NaN       NaN
1     Afghanistan     18.4   2020.0      17.6    2019.0   7020000.0    2020.0
2         Albania     83.1   2023.0      83.1    2023.0   2291000.0    2021.0
3         Algeria     71.2   2022.0      71.2    2022.0  31240000.0    2021.0
4  American Samoa      NaN      NaN       NaN       NaN     18135.0    2021.0

In [11]:
# Cleaning numerical columns

# Drop only if BOTH sources are missing
df = df.dropna(subset=['rate_wb', 'rate_itu'], how='all')

# Create average
df['avg_internet_rate'] = df[['rate_wb', 'rate_itu']].mean(axis=1)

In [13]:
df.head()

,country,rate_wb,year_wb,rate_itu,year_itu,users_cia,year_cia,avg_internet_rate
0,World,67.4,2023.0,67.4,2023.0,NaN,NaN,67.4
1,Afghanistan,18.4,2020.0,17.6,2019.0,7020000.0,2020.0,18.0
2,Albania,83.1,2023.0,83.1,2023.0,2291000.0,2021.0,83.1
3,Algeria,71.2,2022.0,71.2,2022.0,31240000.0,2021.0,71.2
5,Andorra,94.5,2022.0,94.5,2022.0,74260.0,2021.0,94.5

In [14]:
# Remove 'World' row
df = df[df['country'] != 'World']

In [15]:
# Fix the type of year columns, from float to integer type
df['year_wb'] = df['year_wb'].astype('Int64')
df['year_itu'] = df['year_itu'].astype('Int64')
df['year_cia'] = df['year_cia'].astype('Int64')

In [16]:
# Lightly clean cia_users column, and covert their type

df = df.dropna(subset=['users_cia'], how='all')
df['users_cia'] = df['users_cia'].astype('Int64')

In [18]:
# Create a 'latest_year' column, as sometimes year of WB!= year of ITU

df['latest_year'] = df[['year_wb', 'year_itu']].max(axis=1)
df.head()

,country,rate_wb,year_wb,rate_itu,year_itu,users_cia,year_cia,avg_internet_rate,latest_year
1,Afghanistan,18.4,2020,17.6,2019,7020000,2020,18.0,2020
2,Albania,83.1,2023,83.1,2023,2291000,2021,83.1,2023
3,Algeria,71.2,2022,71.2,2022,31240000,2021,71.2,2022
5,Andorra,94.5,2022,94.5,2022,74260,2021,94.5,2022
6,Angola,39.3,2022,39.3,2022,11550000,2021,39.3,2022

In [19]:
# Save cleaned csv file
df.to_csv('internet_usage_cleaned.csv', index=False)